-- Seed suggestions_fiche pour toutes les sous-catégories LASSI
-- Données adaptées au marché dakarois / réalité sénégalaise
-- Sections : type_contenu | sous_categorie_produit | nom_produit | prix

-- Purge préalable pour éviter doublons si rejouée
DELETE FROM public.suggestions_fiche WHERE actif = true;

INSERT INTO public.suggestions_fiche (categorie_id, sous_categorie_id, section, valeur, ordre, actif) VALUES

-- ══════════════════════════════════════════════════════════════
-- CATEGORY : stores
-- ══════════════════════════════════════════════════════════════

-- ── nexx_sow (Tissus / Pagnes) ────────────────────────────────
('stores','nexx_sow','type_contenu','Catalogue',1,true),
('stores','nexx_sow','type_contenu','Tarif',2,true),
('stores','nexx_sow','type_contenu','Liste de tissus',3,true),
('stores','nexx_sow','type_contenu','Prix du marché',4,true),

('stores','nexx_sow','sous_categorie_produit','Tissus wax',1,true),
('stores','nexx_sow','sous_categorie_produit','Bazin',2,true),
('stores','nexx_sow','sous_categorie_produit','Pagnes',3,true),
('stores','nexx_sow','sous_categorie_produit','Dentelles',4,true),
('stores','nexx_sow','sous_categorie_produit','Broderies',5,true),
('stores','nexx_sow','sous_categorie_produit','Voiles',6,true),
('stores','nexx_sow','sous_categorie_produit','Soieries',7,true),

('stores','nexx_sow','nom_produit','Wax Vlisco 6 yards',1,true),
('stores','nexx_sow','nom_produit','Bazin riche brodé',2,true),
('stores','nexx_sow','nom_produit','Pagne super wax',3,true),
('stores','nexx_sow','nom_produit','Tissu ankara',4,true),
('stores','nexx_sow','nom_produit','Bazin ordinaire',5,true),
('stores','nexx_sow','nom_produit','Wax hitarget',6,true),
('stores','nexx_sow','nom_produit','Pagne kente',7,true),
('stores','nexx_sow','nom_produit','Tissu bogolan',8,true),
('stores','nexx_sow','nom_produit','Bazin getzner',9,true),
('stores','nexx_sow','nom_produit','Dentelle brodée',10,true),
('stores','nexx_sow','nom_produit','Voile de coton',11,true),
('stores','nexx_sow','nom_produit','Super wax hollandais',12,true),

('stores','nexx_sow','prix','2 500',1,true),
('stores','nexx_sow','prix','5 000',2,true),
('stores','nexx_sow','prix','8 000',3,true),
('stores','nexx_sow','prix','12 000',4,true),
('stores','nexx_sow','prix','15 000',5,true),
('stores','nexx_sow','prix','25 000',6,true),
('stores','nexx_sow','prix','35 000',7,true),
('stores','nexx_sow','prix','50 000',8,true),

-- ── sombi_ak_thiere (Céréales / Bouillie) ─────────────────────
('stores','sombi_ak_thiere','type_contenu','Tarif',1,true),
('stores','sombi_ak_thiere','type_contenu','Liste de céréales',2,true),
('stores','sombi_ak_thiere','type_contenu','Prix du jour',3,true),
('stores','sombi_ak_thiere','type_contenu','Menu bouillie',4,true),

('stores','sombi_ak_thiere','sous_categorie_produit','Céréales brutes',1,true),
('stores','sombi_ak_thiere','sous_categorie_produit','Farines',2,true),
('stores','sombi_ak_thiere','sous_categorie_produit','Bouillies',3,true),
('stores','sombi_ak_thiere','sous_categorie_produit','Couscous',4,true),
('stores','sombi_ak_thiere','sous_categorie_produit','Condiments',5,true),
('stores','sombi_ak_thiere','sous_categorie_produit','Légumineuses',6,true),

('stores','sombi_ak_thiere','nom_produit','Mil souna',1,true),
('stores','sombi_ak_thiere','nom_produit','Sorgho rouge',2,true),
('stores','sombi_ak_thiere','nom_produit','Maïs blanc',3,true),
('stores','sombi_ak_thiere','nom_produit','Thiéré (couscous mil)',4,true),
('stores','sombi_ak_thiere','nom_produit','Lakh (bouillie mil)',5,true),
('stores','sombi_ak_thiere','nom_produit','Farine de maïs',6,true),
('stores','sombi_ak_thiere','nom_produit','Niébé (haricot blanc)',7,true),
('stores','sombi_ak_thiere','nom_produit','Arachides décortiquées',8,true),
('stores','sombi_ak_thiere','nom_produit','Fonio',9,true),
('stores','sombi_ak_thiere','nom_produit','Sésame',10,true),
('stores','sombi_ak_thiere','nom_produit','Mil sanio',11,true),
('stores','sombi_ak_thiere','nom_produit','Bouillie de mil',12,true),
('stores','sombi_ak_thiere','nom_produit','Couscous de maïs',13,true),

('stores','sombi_ak_thiere','prix','200',1,true),
('stores','sombi_ak_thiere','prix','500',2,true),
('stores','sombi_ak_thiere','prix','1 000',3,true),
('stores','sombi_ak_thiere','prix','1 500',4,true),
('stores','sombi_ak_thiere','prix','2 000',5,true),
('stores','sombi_ak_thiere','prix','3 000',6,true),
('stores','sombi_ak_thiere','prix','5 000',7,true),

-- ── alimentation (Épicerie / Boutique) ─────────────────────────
('stores','alimentation','type_contenu','Catalogue',1,true),
('stores','alimentation','type_contenu','Tarif',2,true),
('stores','alimentation','type_contenu','Liste de prix',3,true),
('stores','alimentation','type_contenu','Promotions',4,true),

('stores','alimentation','sous_categorie_produit','Riz et céréales',1,true),
('stores','alimentation','sous_categorie_produit','Huiles et graisses',2,true),
('stores','alimentation','sous_categorie_produit','Conserves',3,true),
('stores','alimentation','sous_categorie_produit','Produits laitiers',4,true),
('stores','alimentation','sous_categorie_produit','Condiments',5,true),
('stores','alimentation','sous_categorie_produit','Boissons',6,true),
('stores','alimentation','sous_categorie_produit','Sucre et sel',7,true),

('stores','alimentation','nom_produit','Riz parfumé 25kg',1,true),
('stores','alimentation','nom_produit','Huile Jumbo 5L',2,true),
('stores','alimentation','nom_produit','Sucre cristallisé 1kg',3,true),
('stores','alimentation','nom_produit','Lait concentré Nestlé',4,true),
('stores','alimentation','nom_produit','Tomate concentrée',5,true),
('stores','alimentation','nom_produit','Savon Omo 1kg',6,true),
('stores','alimentation','nom_produit','Cube Maggi',7,true),
('stores','alimentation','nom_produit','Bissap séché',8,true),
('stores','alimentation','nom_produit','Huile de palme',9,true),
('stores','alimentation','nom_produit','Sel fin 1kg',10,true),
('stores','alimentation','nom_produit','Farine de blé 5kg',11,true),
('stores','alimentation','nom_produit','Haricot niébé 1kg',12,true),

('stores','alimentation','prix','500',1,true),
('stores','alimentation','prix','1 000',2,true),
('stores','alimentation','prix','2 000',3,true),
('stores','alimentation','prix','3 500',4,true),
('stores','alimentation','prix','5 000',5,true),
('stores','alimentation','prix','7 500',6,true),
('stores','alimentation','prix','10 000',7,true),
('stores','alimentation','prix','15 000',8,true),

-- ── quincaillerie ──────────────────────────────────────────────
('stores','quincaillerie','type_contenu','Catalogue',1,true),
('stores','quincaillerie','type_contenu','Tarif',2,true),
('stores','quincaillerie','type_contenu','Liste de matériaux',3,true),
('stores','quincaillerie','type_contenu','Devis',4,true),
('stores','quincaillerie','type_contenu','Prix du marché',5,true),

('stores','quincaillerie','sous_categorie_produit','Ciment et gros œuvre',1,true),
('stores','quincaillerie','sous_categorie_produit','Outillage',2,true),
('stores','quincaillerie','sous_categorie_produit','Visserie et fixations',3,true),
('stores','quincaillerie','sous_categorie_produit','Plomberie',4,true),
('stores','quincaillerie','sous_categorie_produit','Électricité',5,true),
('stores','quincaillerie','sous_categorie_produit','Peinture',6,true),
('stores','quincaillerie','sous_categorie_produit','Bois et menuiserie',7,true),

('stores','quincaillerie','nom_produit','Ciment CPA 50kg',1,true),
('stores','quincaillerie','nom_produit','Fer à béton 8mm',2,true),
('stores','quincaillerie','nom_produit','Clous assortis 1kg',3,true),
('stores','quincaillerie','nom_produit','Vis à bois 3×30',4,true),
('stores','quincaillerie','nom_produit','Colle carrelage 25kg',5,true),
('stores','quincaillerie','nom_produit','Tuyau PVC 2 pouces',6,true),
('stores','quincaillerie','nom_produit','Câble électrique 2,5mm',7,true),
('stores','quincaillerie','nom_produit','Peinture glycéro 4L',8,true),
('stores','quincaillerie','nom_produit','Mèche à béton 10mm',9,true),
('stores','quincaillerie','nom_produit','Charnière acier',10,true),
('stores','quincaillerie','nom_produit','Cadenas Yale',11,true),
('stores','quincaillerie','nom_produit','Planche bois 3m',12,true),

('stores','quincaillerie','prix','500',1,true),
('stores','quincaillerie','prix','1 500',2,true),
('stores','quincaillerie','prix','3 000',3,true),
('stores','quincaillerie','prix','5 000',4,true),
('stores','quincaillerie','prix','8 000',5,true),
('stores','quincaillerie','prix','12 000',6,true),
('stores','quincaillerie','prix','20 000',7,true),
('stores','quincaillerie','prix','35 000',8,true),

-- ══════════════════════════════════════════════════════════════
-- CATEGORY : tangana
-- ══════════════════════════════════════════════════════════════

-- ── tangana (Gargote / Plats du jour) ─────────────────────────
('tangana','tangana','type_contenu','Menu du jour',1,true),
('tangana','tangana','type_contenu','Tarif',2,true),
('tangana','tangana','type_contenu','Carte des plats',3,true),
('tangana','tangana','type_contenu','Prix fixe',4,true),

('tangana','tangana','sous_categorie_produit','Riz et plats en sauce',1,true),
('tangana','tangana','sous_categorie_produit','Grillades',2,true),
('tangana','tangana','sous_categorie_produit','Accompagnements',3,true),
('tangana','tangana','sous_categorie_produit','Soupes',4,true),
('tangana','tangana','sous_categorie_produit','Boissons',5,true),
('tangana','tangana','sous_categorie_produit','Plats végétariens',6,true),

('tangana','tangana','nom_produit','Thiéboudienne rouge',1,true),
('tangana','tangana','nom_produit','Thiéboudienne blanc',2,true),
('tangana','tangana','nom_produit','Yassa poulet',3,true),
('tangana','tangana','nom_produit','Mafé bœuf',4,true),
('tangana','tangana','nom_produit','Thiébou yapp',5,true),
('tangana','tangana','nom_produit','Domoda',6,true),
('tangana','tangana','nom_produit','Caldou',7,true),
('tangana','tangana','nom_produit','Supekanja (soupe gombo)',8,true),
('tangana','tangana','nom_produit','Benachin',9,true),
('tangana','tangana','nom_produit','Mboum (haricot)',10,true),
('tangana','tangana','nom_produit','Yassa poisson',11,true),

('tangana','tangana','prix','500',1,true),
('tangana','tangana','prix','1 000',2,true),
('tangana','tangana','prix','1 500',3,true),
('tangana','tangana','prix','2 000',4,true),
('tangana','tangana','prix','2 500',5,true),
('tangana','tangana','prix','3 000',6,true),
('tangana','tangana','prix','3 500',7,true),

-- ── ndeki (Mama ndeki / Cuisine familiale) ────────────────────
('tangana','ndeki','type_contenu','Menu du jour',1,true),
('tangana','ndeki','type_contenu','Tarif',2,true),
('tangana','ndeki','type_contenu','Plats disponibles',3,true),
('tangana','ndeki','type_contenu','Prix du jour',4,true),

('tangana','ndeki','sous_categorie_produit','Plats familiaux',1,true),
('tangana','ndeki','sous_categorie_produit','Plats en sauce',2,true),
('tangana','ndeki','sous_categorie_produit','Riz',3,true),
('tangana','ndeki','sous_categorie_produit','Accompagnements',4,true),
('tangana','ndeki','sous_categorie_produit','Boissons locales',5,true),

('tangana','ndeki','nom_produit','Thiéboudienne maison',1,true),
('tangana','ndeki','nom_produit','Mafé poulet',2,true),
('tangana','ndeki','nom_produit','Yassa poisson',3,true),
('tangana','ndeki','nom_produit','Soupou kandia',4,true),
('tangana','ndeki','nom_produit','Riz au gras',5,true),
('tangana','ndeki','nom_produit','Thiébou beurre',6,true),
('tangana','ndeki','nom_produit','Lakh bu dëkk',7,true),
('tangana','ndeki','nom_produit','Sombi (riz au lait)',8,true),
('tangana','ndeki','nom_produit','Haricot beurre',9,true),
('tangana','ndeki','nom_produit','Ceebu jen brisé',10,true),
('tangana','ndeki','nom_produit','Mbaxal u saloum',11,true),

('tangana','ndeki','prix','300',1,true),
('tangana','ndeki','prix','500',2,true),
('tangana','ndeki','prix','750',3,true),
('tangana','ndeki','prix','1 000',4,true),
('tangana','ndeki','prix','1 500',5,true),
('tangana','ndeki','prix','2 000',6,true),
('tangana','ndeki','prix','2 500',7,true),

-- ── soupe ─────────────────────────────────────────────────────
('tangana','soupe','type_contenu','Menu du jour',1,true),
('tangana','soupe','type_contenu','Tarif',2,true),
('tangana','soupe','type_contenu','Liste de soupes',3,true),
('tangana','soupe','type_contenu','Prix fixe',4,true),

('tangana','soupe','sous_categorie_produit','Soupes de poisson',1,true),
('tangana','soupe','sous_categorie_produit','Soupes de viande',2,true),
('tangana','soupe','sous_categorie_produit','Bouillons',3,true),
('tangana','soupe','sous_categorie_produit','Soupes végétales',4,true),
('tangana','soupe','sous_categorie_produit','Accompagnements',5,true),

('tangana','soupe','nom_produit','Soupe kandja (gombo)',1,true),
('tangana','soupe','nom_produit','Soupe de poisson thiof',2,true),
('tangana','soupe','nom_produit','Bouillon de bœuf',3,true),
('tangana','soupe','nom_produit','Soupe yaboye (crevettes)',4,true),
('tangana','soupe','nom_produit','Soupe de mouton',5,true),
('tangana','soupe','nom_produit','Soupe kaldou',6,true),
('tangana','soupe','nom_produit','Soupe de légumes',7,true),
('tangana','soupe','nom_produit','Soupe aux arachides',8,true),
('tangana','soupe','nom_produit','Bouillon de poulet',9,true),
('tangana','soupe','nom_produit','Broth de poisson séché',10,true),

('tangana','soupe','prix','200',1,true),
('tangana','soupe','prix','300',2,true),
('tangana','soupe','prix','500',3,true),
('tangana','soupe','prix','750',4,true),
('tangana','soupe','prix','1 000',5,true),
('tangana','soupe','prix','1 500',6,true),
('tangana','soupe','prix','2 000',7,true),

-- ── cafe_wass (Café Touba / Ataya) ────────────────────────────
('tangana','cafe_wass','type_contenu','Menu boissons',1,true),
('tangana','cafe_wass','type_contenu','Tarif',2,true),
('tangana','cafe_wass','type_contenu','Carte du matin',3,true),
('tangana','cafe_wass','type_contenu','Prix fixe',4,true),

('tangana','cafe_wass','sous_categorie_produit','Cafés et thés',1,true),
('tangana','cafe_wass','sous_categorie_produit','Boissons chaudes',2,true),
('tangana','cafe_wass','sous_categorie_produit','Petit-déjeuner',3,true),
('tangana','cafe_wass','sous_categorie_produit','Ataya',4,true),
('tangana','cafe_wass','sous_categorie_produit','Jus naturels',5,true),

('tangana','cafe_wass','nom_produit','Café Touba',1,true),
('tangana','cafe_wass','nom_produit','Café noir',2,true),
('tangana','cafe_wass','nom_produit','Thé Lipton au lait',3,true),
('tangana','cafe_wass','nom_produit','Ataya (thé vert)',4,true),
('tangana','cafe_wass','nom_produit','Café au lait Nescafé',5,true),
('tangana','cafe_wass','nom_produit','Kinkeliba infusion',6,true),
('tangana','cafe_wass','nom_produit','Chocolat chaud',7,true),
('tangana','cafe_wass','nom_produit','Café Touba spécial',8,true),
('tangana','cafe_wass','nom_produit','Thé à la menthe',9,true),
('tangana','cafe_wass','nom_produit','Pain beurre café',10,true),
('tangana','cafe_wass','nom_produit','Lait chaud',11,true),
('tangana','cafe_wass','nom_produit','Bissap chaud',12,true),

('tangana','cafe_wass','prix','100',1,true),
('tangana','cafe_wass','prix','150',2,true),
('tangana','cafe_wass','prix','200',3,true),
('tangana','cafe_wass','prix','250',4,true),
('tangana','cafe_wass','prix','300',5,true),
('tangana','cafe_wass','prix','500',6,true),
('tangana','cafe_wass','prix','750',7,true),

-- ── beignet_fataya ────────────────────────────────────────────
('tangana','beignet_fataya','type_contenu','Menu',1,true),
('tangana','beignet_fataya','type_contenu','Tarif',2,true),
('tangana','beignet_fataya','type_contenu','Liste de produits',3,true),
('tangana','beignet_fataya','type_contenu','Prix du jour',4,true),

('tangana','beignet_fataya','sous_categorie_produit','Beignets sucrés',1,true),
('tangana','beignet_fataya','sous_categorie_produit','Beignets salés',2,true),
('tangana','beignet_fataya','sous_categorie_produit','Fataya',3,true),
('tangana','beignet_fataya','sous_categorie_produit','Accara',4,true),
('tangana','beignet_fataya','sous_categorie_produit','Frits divers',5,true),

('tangana','beignet_fataya','nom_produit','Fataya au poisson',1,true),
('tangana','beignet_fataya','nom_produit','Accara (beignet niébé)',2,true),
('tangana','beignet_fataya','nom_produit','Beignet de banane',3,true),
('tangana','beignet_fataya','nom_produit','Nem frit',4,true),
('tangana','beignet_fataya','nom_produit','Beignet de maïs',5,true),
('tangana','beignet_fataya','nom_produit','Beignet soufflé',6,true),
('tangana','beignet_fataya','nom_produit','Fataya à la viande',7,true),
('tangana','beignet_fataya','nom_produit','Beignet de mil',8,true),
('tangana','beignet_fataya','nom_produit','Samoussa',9,true),
('tangana','beignet_fataya','nom_produit','Beignet patate douce',10,true),
('tangana','beignet_fataya','nom_produit','Puff-puff',11,true),
('tangana','beignet_fataya','nom_produit','Beignet haricot',12,true),

('tangana','beignet_fataya','prix','25',1,true),
('tangana','beignet_fataya','prix','50',2,true),
('tangana','beignet_fataya','prix','100',3,true),
('tangana','beignet_fataya','prix','150',4,true),
('tangana','beignet_fataya','prix','200',5,true),
('tangana','beignet_fataya','prix','300',6,true),
('tangana','beignet_fataya','prix','500',7,true),

-- ══════════════════════════════════════════════════════════════
-- CATEGORY : bakery
-- ══════════════════════════════════════════════════════════════

-- ── boulangerie ───────────────────────────────────────────────
('bakery','boulangerie','type_contenu','Catalogue',1,true),
('bakery','boulangerie','type_contenu','Tarif',2,true),
('bakery','boulangerie','type_contenu','Liste de pains',3,true),
('bakery','boulangerie','type_contenu','Menu boulangerie',4,true),
('bakery','boulangerie','type_contenu','Prix du jour',5,true),

('bakery','boulangerie','sous_categorie_produit','Pains traditionnels',1,true),
('bakery','boulangerie','sous_categorie_produit','Pains spéciaux',2,true),
('bakery','boulangerie','sous_categorie_produit','Viennoiseries',3,true),
('bakery','boulangerie','sous_categorie_produit','Sandwichs',4,true),
('bakery','boulangerie','sous_categorie_produit','Pains sucrés',5,true),

('bakery','boulangerie','nom_produit','Pain baguette 200g',1,true),
('bakery','boulangerie','nom_produit','Tapalapa (pain mil)',2,true),
('bakery','boulangerie','nom_produit','Pain de mie tranché',3,true),
('bakery','boulangerie','nom_produit','Croissant beurre',4,true),
('bakery','boulangerie','nom_produit','Pain complet',5,true),
('bakery','boulangerie','nom_produit','Sandwich poulet',6,true),
('bakery','boulangerie','nom_produit','Pain au chocolat',7,true),
('bakery','boulangerie','nom_produit','Brioche nature',8,true),
('bakery','boulangerie','nom_produit','Pain hamburger',9,true),
('bakery','boulangerie','nom_produit','Baguette tradition',10,true),
('bakery','boulangerie','nom_produit','Pain fonio',11,true),

('bakery','boulangerie','prix','150',1,true),
('bakery','boulangerie','prix','200',2,true),
('bakery','boulangerie','prix','300',3,true),
('bakery','boulangerie','prix','500',4,true),
('bakery','boulangerie','prix','750',5,true),
('bakery','boulangerie','prix','1 000',6,true),
('bakery','boulangerie','prix','1 500',7,true),
('bakery','boulangerie','prix','2 500',8,true),

-- ── patisserie ────────────────────────────────────────────────
('bakery','patisserie','type_contenu','Catalogue',1,true),
('bakery','patisserie','type_contenu','Tarif',2,true),
('bakery','patisserie','type_contenu','Menu pâtisserie',3,true),
('bakery','patisserie','type_contenu','Liste gâteaux',4,true),
('bakery','patisserie','type_contenu','Prix sur commande',5,true),

('bakery','patisserie','sous_categorie_produit','Gâteaux anniversaire',1,true),
('bakery','patisserie','sous_categorie_produit','Petits gâteaux',2,true),
('bakery','patisserie','sous_categorie_produit','Tartes',3,true),
('bakery','patisserie','sous_categorie_produit','Chocolaterie',4,true),
('bakery','patisserie','sous_categorie_produit','Entremets',5,true),
('bakery','patisserie','sous_categorie_produit','Mignardises',6,true),

('bakery','patisserie','nom_produit','Gâteau anniversaire',1,true),
('bakery','patisserie','nom_produit','Tarte aux fruits',2,true),
('bakery','patisserie','nom_produit','Éclair au chocolat',3,true),
('bakery','patisserie','nom_produit','Mille-feuille',4,true),
('bakery','patisserie','nom_produit','Fondant chocolat',5,true),
('bakery','patisserie','nom_produit','Cheesecake',6,true),
('bakery','patisserie','nom_produit','Madeleine beurre',7,true),
('bakery','patisserie','nom_produit','Baba au rhum',8,true),
('bakery','patisserie','nom_produit','Mousse au chocolat',9,true),
('bakery','patisserie','nom_produit','Profiteroles',10,true),
('bakery','patisserie','nom_produit','Bavarois framboise',11,true),
('bakery','patisserie','nom_produit','Cookies noix de coco',12,true),

('bakery','patisserie','prix','500',1,true),
('bakery','patisserie','prix','1 000',2,true),
('bakery','patisserie','prix','1 500',3,true),
('bakery','patisserie','prix','2 500',4,true),
('bakery','patisserie','prix','5 000',5,true),
('bakery','patisserie','prix','10 000',6,true),
('bakery','patisserie','prix','15 000',7,true),
('bakery','patisserie','prix','25 000',8,true),

-- ══════════════════════════════════════════════════════════════
-- CATEGORY : food
-- ══════════════════════════════════════════════════════════════

-- ── restaurant ────────────────────────────────────────────────
('food','restaurant','type_contenu','Carte du restaurant',1,true),
('food','restaurant','type_contenu','Menu du jour',2,true),
('food','restaurant','type_contenu','Tarif',3,true),
('food','restaurant','type_contenu','Menu spécial',4,true),
('food','restaurant','type_contenu','Menu groupe',5,true),

('food','restaurant','sous_categorie_produit','Entrées',1,true),
('food','restaurant','sous_categorie_produit','Plats principaux',2,true),
('food','restaurant','sous_categorie_produit','Grillades',3,true),
('food','restaurant','sous_categorie_produit','Poissons',4,true),
('food','restaurant','sous_categorie_produit','Desserts',5,true),
('food','restaurant','sous_categorie_produit','Boissons',6,true),
('food','restaurant','sous_categorie_produit','Cuisine internationale',7,true),

('food','restaurant','nom_produit','Thiéboudienne prestige',1,true),
('food','restaurant','nom_produit','Yassa poulet grillé',2,true),
('food','restaurant','nom_produit','Mafé royal',3,true),
('food','restaurant','nom_produit','Brochettes mixtes',4,true),
('food','restaurant','nom_produit','Poisson thiof grillé',5,true),
('food','restaurant','nom_produit','Poulet rôti',6,true),
('food','restaurant','nom_produit','Steak frites',7,true),
('food','restaurant','nom_produit','Salade niçoise',8,true),
('food','restaurant','nom_produit','Crevettes sautées',9,true),
('food','restaurant','nom_produit','Côtelettes d agneau',10,true),
('food','restaurant','nom_produit','Tiébou dieun spécial',11,true),
('food','restaurant','nom_produit','Burger artisanal',12,true),

('food','restaurant','prix','2 000',1,true),
('food','restaurant','prix','3 000',2,true),
('food','restaurant','prix','4 000',3,true),
('food','restaurant','prix','5 000',4,true),
('food','restaurant','prix','7 500',5,true),
('food','restaurant','prix','10 000',6,true),
('food','restaurant','prix','15 000',7,true),
('food','restaurant','prix','20 000',8,true),

-- ── fastfood ──────────────────────────────────────────────────
('food','fastfood','type_contenu','Menu',1,true),
('food','fastfood','type_contenu','Carte',2,true),
('food','fastfood','type_contenu','Formules',3,true),
('food','fastfood','type_contenu','Tarif',4,true),
('food','fastfood','type_contenu','Menu enfant',5,true),

('food','fastfood','sous_categorie_produit','Burgers',1,true),
('food','fastfood','sous_categorie_produit','Sandwichs',2,true),
('food','fastfood','sous_categorie_produit','Pizzas',3,true),
('food','fastfood','sous_categorie_produit','Poulet frit',4,true),
('food','fastfood','sous_categorie_produit','Accompagnements',5,true),
('food','fastfood','sous_categorie_produit','Boissons',6,true),
('food','fastfood','sous_categorie_produit','Desserts',7,true),

('food','fastfood','nom_produit','Burger classic',1,true),
('food','fastfood','nom_produit','Burger poulet croustillant',2,true),
('food','fastfood','nom_produit','Sandwich jambon fromage',3,true),
('food','fastfood','nom_produit','Pizza margherita',4,true),
('food','fastfood','nom_produit','Frites maison',5,true),
('food','fastfood','nom_produit','Nuggets poulet 6pc',6,true),
('food','fastfood','nom_produit','Hot-dog',7,true),
('food','fastfood','nom_produit','Wrap poulet',8,true),
('food','fastfood','nom_produit','Club sandwich',9,true),
('food','fastfood','nom_produit','Burger double beef',10,true),
('food','fastfood','nom_produit','Pizza 4 fromages',11,true),
('food','fastfood','nom_produit','Onion rings',12,true),

('food','fastfood','prix','1 500',1,true),
('food','fastfood','prix','2 000',2,true),
('food','fastfood','prix','2 500',3,true),
('food','fastfood','prix','3 000',4,true),
('food','fastfood','prix','3 500',5,true),
('food','fastfood','prix','5 000',6,true),
('food','fastfood','prix','7 500',7,true),

-- ── malibu (Poisson braisé / Maquis) ─────────────────────────
('food','malibu','type_contenu','Carte des grillades',1,true),
('food','malibu','type_contenu','Tarif',2,true),
('food','malibu','type_contenu','Menu maquis',3,true),
('food','malibu','type_contenu','Prix du poisson',4,true),
('food','malibu','type_contenu','Menu du soir',5,true),

('food','malibu','sous_categorie_produit','Poissons grillés',1,true),
('food','malibu','sous_categorie_produit','Fruits de mer',2,true),
('food','malibu','sous_categorie_produit','Viandes grillées',3,true),
('food','malibu','sous_categorie_produit','Accompagnements',4,true),
('food','malibu','sous_categorie_produit','Salades',5,true),
('food','malibu','sous_categorie_produit','Boissons fraîches',6,true),

('food','malibu','nom_produit','Thiof grillé entier',1,true),
('food','malibu','nom_produit','Capitaine braisé',2,true),
('food','malibu','nom_produit','Crevettes grillées',3,true),
('food','malibu','nom_produit','Homard grillé',4,true),
('food','malibu','nom_produit','Barracuda braisé',5,true),
('food','malibu','nom_produit','Brochettes de mer',6,true),
('food','malibu','nom_produit','Calamars frits',7,true),
('food','malibu','nom_produit','Sole grillée',8,true),
('food','malibu','nom_produit','Mérou entier',9,true),
('food','malibu','nom_produit','Poisson braisé sauce oignon',10,true),
('food','malibu','nom_produit','Salade de poulpe',11,true),
('food','malibu','nom_produit','Crevettes sauce tartare',12,true),

('food','malibu','prix','3 000',1,true),
('food','malibu','prix','5 000',2,true),
('food','malibu','prix','7 500',3,true),
('food','malibu','prix','10 000',4,true),
('food','malibu','prix','15 000',5,true),
('food','malibu','prix','20 000',6,true),
('food','malibu','prix','35 000',7,true),

-- ── dibiterie ─────────────────────────────────────────────────
('food','dibiterie','type_contenu','Tarif',1,true),
('food','dibiterie','type_contenu','Menu dibi',2,true),
('food','dibiterie','type_contenu','Liste de viandes',3,true),
('food','dibiterie','type_contenu','Prix au kilo',4,true),
('food','dibiterie','type_contenu','Menu brochettes',5,true),

('food','dibiterie','sous_categorie_produit','Dibi mouton',1,true),
('food','dibiterie','sous_categorie_produit','Brochettes',2,true),
('food','dibiterie','sous_categorie_produit','Abats',3,true),
('food','dibiterie','sous_categorie_produit','Accompagnements',4,true),
('food','dibiterie','sous_categorie_produit','Viandes spéciales',5,true),

('food','dibiterie','nom_produit','Dibi mouton 1/4 kg',1,true),
('food','dibiterie','nom_produit','Brochette de mouton',2,true),
('food','dibiterie','nom_produit','Brochette de bœuf',3,true),
('food','dibiterie','nom_produit','Foie grillé',4,true),
('food','dibiterie','nom_produit','Rognons grillés',5,true),
('food','dibiterie','nom_produit','Côtelettes mouton',6,true),
('food','dibiterie','nom_produit','Dibi bœuf',7,true),
('food','dibiterie','nom_produit','Merguez maison',8,true),
('food','dibiterie','nom_produit','Jakatu (intestins grillés)',9,true),
('food','dibiterie','nom_produit','Poulet dibi',10,true),
('food','dibiterie','nom_produit','Agneau grillé',11,true),
('food','dibiterie','nom_produit','Côtes d agneau',12,true),

('food','dibiterie','prix','1 000',1,true),
('food','dibiterie','prix','1 500',2,true),
('food','dibiterie','prix','2 000',3,true),
('food','dibiterie','prix','2 500',4,true),
('food','dibiterie','prix','3 000',5,true),
('food','dibiterie','prix','4 000',6,true),
('food','dibiterie','prix','6 000',7,true),
('food','dibiterie','prix','8 000',8,true),

-- ── seras (Séraas / Cuisine ivoirienne) ──────────────────────
('food','seras','type_contenu','Menu du jour',1,true),
('food','seras','type_contenu','Carte',2,true),
('food','seras','type_contenu','Tarif',3,true),
('food','seras','type_contenu','Plats spéciaux',4,true),
('food','seras','type_contenu','Menu ivoirien',5,true),

('food','seras','sous_categorie_produit','Attiéké',1,true),
('food','seras','sous_categorie_produit','Kedjenou',2,true),
('food','seras','sous_categorie_produit','Grillades ivoiriennes',3,true),
('food','seras','sous_categorie_produit','Aloko',4,true),
('food','seras','sous_categorie_produit','Sauces africaines',5,true),
('food','seras','sous_categorie_produit','Boissons',6,true),

('food','seras','nom_produit','Attiéké poisson braisé',1,true),
('food','seras','nom_produit','Kedjenou poulet',2,true),
('food','seras','nom_produit','Attiéké placali',3,true),
('food','seras','nom_produit','Aloko (banane plantain frite)',4,true),
('food','seras','nom_produit','Poisson braisé sauce tomate',5,true),
('food','seras','nom_produit','Garba (thon attiéké)',6,true),
('food','seras','nom_produit','Foutou banane sauce graine',7,true),
('food','seras','nom_produit','Sauce graine',8,true),
('food','seras','nom_produit','Attiéké crevettes',9,true),
('food','seras','nom_produit','Poulet braisé ivoirien',10,true),
('food','seras','nom_produit','Fufu sauce arachide',11,true),

('food','seras','prix','1 000',1,true),
('food','seras','prix','1 500',2,true),
('food','seras','prix','2 000',3,true),
('food','seras','prix','2 500',4,true),
('food','seras','prix','3 000',5,true),
('food','seras','prix','4 000',6,true),
('food','seras','prix','5 000',7,true),

-- ── jus (Jus & Boissons) ──────────────────────────────────────
('food','jus','type_contenu','Carte des jus',1,true),
('food','jus','type_contenu','Menu',2,true),
('food','jus','type_contenu','Tarif',3,true),
('food','jus','type_contenu','Liste des boissons',4,true),
('food','jus','type_contenu','Ardoise du jour',5,true),

('food','jus','sous_categorie_produit','Jus de fruits locaux',1,true),
('food','jus','sous_categorie_produit','Infusions & Décoctions',2,true),
('food','jus','sous_categorie_produit','Jus importés',3,true),
('food','jus','sous_categorie_produit','Smoothie',4,true),
('food','jus','sous_categorie_produit','Eau & Sodas',5,true),
('food','jus','sous_categorie_produit','Jus détox',6,true),
('food','jus','sous_categorie_produit','Boissons chaudes',7,true),

('food','jus','nom_produit','Bissap',1,true),
('food','jus','nom_produit','Bouye',2,true),
('food','jus','nom_produit','Tamarin',3,true),
('food','jus','nom_produit','Ditakh',4,true),
('food','jus','nom_produit','Gingembre',5,true),
('food','jus','nom_produit','Gingembre-Citron',6,true),
('food','jus','nom_produit','Jus de Mangue',7,true),
('food','jus','nom_produit','Jus de Pastèque',8,true),
('food','jus','nom_produit','Corossol',9,true),
('food','jus','nom_produit','Dakhar (Oseille fraîche)',10,true),
('food','jus','nom_produit','Jus de Bissap-Gingembre',11,true),
('food','jus','nom_produit','Jus de Baobab',12,true),
('food','jus','nom_produit','Cocktail maison',13,true),

('food','jus','prix','200',1,true),
('food','jus','prix','300',2,true),
('food','jus','prix','500',3,true),
('food','jus','prix','750',4,true),
('food','jus','prix','1 000',5,true),
('food','jus','prix','1 500',6,true),
('food','jus','prix','2 000',7,true),
('food','jus','prix','2 500',8,true),

-- ── snack (Snack & Gourmandise) ───────────────────────────────
('food','snack','type_contenu','Menu',1,true),
('food','snack','type_contenu','Carte snack',2,true),
('food','snack','type_contenu','Tarif',3,true),
('food','snack','type_contenu','Liste des articles',4,true),
('food','snack','type_contenu','Ardoise du jour',5,true),

('food','snack','sous_categorie_produit','Sandwich & Burger',1,true),
('food','snack','sous_categorie_produit','Friterie',2,true),
('food','snack','sous_categorie_produit','Biscuits & Gâteaux',3,true),
('food','snack','sous_categorie_produit','Chips & Crackers',4,true),
('food','snack','sous_categorie_produit','Bonbons & Confiserie',5,true),
('food','snack','sous_categorie_produit','Brochettes',6,true),
('food','snack','sous_categorie_produit','Omelette & Œufs',7,true),

('food','snack','nom_produit','Sandwich Poulet',1,true),
('food','snack','nom_produit','Sandwich Thon',2,true),
('food','snack','nom_produit','Omelette baguette',3,true),
('food','snack','nom_produit','Chawarma',4,true),
('food','snack','nom_produit','Alloco (Banane frite)',5,true),
('food','snack','nom_produit','Fataya',6,true),
('food','snack','nom_produit','Nems',7,true),
('food','snack','nom_produit','Samoussa',8,true),
('food','snack','nom_produit','Brochette de bœuf',9,true),
('food','snack','nom_produit','Dibi',10,true),
('food','snack','nom_produit','Chips maison',11,true),
('food','snack','nom_produit','Beignets haricots (Accara)',12,true),
('food','snack','nom_produit','Pain beurre',13,true),
('food','snack','nom_produit','Thiakry',14,true),

('food','snack','prix','200',1,true),
('food','snack','prix','350',2,true),
('food','snack','prix','500',3,true),
('food','snack','prix','750',4,true),
('food','snack','prix','1 000',5,true),
('food','snack','prix','1 500',6,true),
('food','snack','prix','2 000',7,true),
('food','snack','prix','2 500',8,true),
('food','snack','prix','3 000',9,true),

-- ══════════════════════════════════════════════════════════════
-- CATEGORY : fruiterie
-- ══════════════════════════════════════════════════════════════

-- ── fruits (Fruits frais) ─────────────────────────────────────
('fruiterie','fruits','type_contenu','Catalogue',1,true),
('fruiterie','fruits','type_contenu','Tarif',2,true),
('fruiterie','fruits','type_contenu','Liste des fruits',3,true),
('fruiterie','fruits','type_contenu','Prix du jour',4,true),
('fruiterie','fruits','type_contenu','Ardoise',5,true),

('fruiterie','fruits','sous_categorie_produit','Fruits tropicaux',1,true),
('fruiterie','fruits','sous_categorie_produit','Agrumes',2,true),
('fruiterie','fruits','sous_categorie_produit','Fruits de saison',3,true),
('fruiterie','fruits','sous_categorie_produit','Fruits importés',4,true),
('fruiterie','fruits','sous_categorie_produit','Panier de fruits',5,true),
('fruiterie','fruits','sous_categorie_produit','Fruits coupés',6,true),

('fruiterie','fruits','nom_produit','Mangue Kent',1,true),
('fruiterie','fruits','nom_produit','Mangue Boukodiagne',2,true),
('fruiterie','fruits','nom_produit','Pastèque',3,true),
('fruiterie','fruits','nom_produit','Papaye',4,true),
('fruiterie','fruits','nom_produit','Banane',5,true),
('fruiterie','fruits','nom_produit','Orange',6,true),
('fruiterie','fruits','nom_produit','Citron',7,true),
('fruiterie','fruits','nom_produit','Ananas',8,true),
('fruiterie','fruits','nom_produit','Melon',9,true),
('fruiterie','fruits','nom_produit','Pomme importée',10,true),
('fruiterie','fruits','nom_produit','Raisin',11,true),
('fruiterie','fruits','nom_produit','Goyave',12,true),
('fruiterie','fruits','nom_produit','Tamarin frais',13,true),
('fruiterie','fruits','nom_produit','Noix de coco',14,true),

('fruiterie','fruits','prix','200',1,true),
('fruiterie','fruits','prix','350',2,true),
('fruiterie','fruits','prix','500',3,true),
('fruiterie','fruits','prix','750',4,true),
('fruiterie','fruits','prix','1 000',5,true),
('fruiterie','fruits','prix','1 500',6,true),
('fruiterie','fruits','prix','2 000',7,true),
('fruiterie','fruits','prix','3 000',8,true),
('fruiterie','fruits','prix','5 000',9,true),

-- ── fruits_marines (Fruits marinés) ──────────────────────────
('fruiterie','fruits_marines','type_contenu','Carte',1,true),
('fruiterie','fruits_marines','type_contenu','Tarif',2,true),
('fruiterie','fruits_marines','type_contenu','Menu',3,true),
('fruiterie','fruits_marines','type_contenu','Liste des articles',4,true),
('fruiterie','fruits_marines','type_contenu','Ardoise du jour',5,true),

('fruiterie','fruits_marines','sous_categorie_produit','Fruits pimentés',1,true),
('fruiterie','fruits_marines','sous_categorie_produit','Fruits sucrés-salés',2,true),
('fruiterie','fruits_marines','sous_categorie_produit','Marinades épicées',3,true),
('fruiterie','fruits_marines','sous_categorie_produit','Sauces accompagnement',4,true),
('fruiterie','fruits_marines','sous_categorie_produit','Assortiments',5,true),
('fruiterie','fruits_marines','sous_categorie_produit','Fruits au vinaigre',6,true),

('fruiterie','fruits_marines','nom_produit','Mangue verte pimentée',1,true),
('fruiterie','fruits_marines','nom_produit','Ditakh mariné',2,true),
('fruiterie','fruits_marines','nom_produit','Tamarin pimenté',3,true),
('fruiterie','fruits_marines','nom_produit','Corossol assaisonné',4,true),
('fruiterie','fruits_marines','nom_produit','Bissap confit',5,true),
('fruiterie','fruits_marines','nom_produit','Papaye verte épicée',6,true),
('fruiterie','fruits_marines','nom_produit','Goyave marinée',7,true),
('fruiterie','fruits_marines','nom_produit','Citron confit',8,true),
('fruiterie','fruits_marines','nom_produit','Noix de cajou pimentée',9,true),
('fruiterie','fruits_marines','nom_produit','Assortiment fruits marinés',10,true),
('fruiterie','fruits_marines','nom_produit','Mangue-Gingembre',11,true),
('fruiterie','fruits_marines','nom_produit','Pastèque pimentée',12,true),

('fruiterie','fruits_marines','prix','200',1,true),
('fruiterie','fruits_marines','prix','350',2,true),
('fruiterie','fruits_marines','prix','500',3,true),
('fruiterie','fruits_marines','prix','750',4,true),
('fruiterie','fruits_marines','prix','1 000',5,true),
('fruiterie','fruits_marines','prix','1 500',6,true),
('fruiterie','fruits_marines','prix','2 000',7,true),
('fruiterie','fruits_marines','prix','2 500',8,true),

-- ══════════════════════════════════════════════════════════════
-- CATEGORY : hair
-- ══════════════════════════════════════════════════════════════

-- ── hommes (Coiffeur Hommes) ──────────────────────────────────
('hair','hommes','type_contenu','Tarif',1,true),
('hair','hommes','type_contenu','Menu de prestations',2,true),
('hair','hommes','type_contenu','Carte des services',3,true),
('hair','hommes','type_contenu','Catalogue',4,true),
('hair','hommes','type_contenu','Liste des soins',5,true),

('hair','hommes','sous_categorie_produit','Coupe & Dégradé',1,true),
('hair','hommes','sous_categorie_produit','Rasage & Barbe',2,true),
('hair','hommes','sous_categorie_produit','Soin du visage',3,true),
('hair','hommes','sous_categorie_produit','Coiffures spéciales',4,true),
('hair','hommes','sous_categorie_produit','Traitements capillaires',5,true),
('hair','hommes','sous_categorie_produit','Coupe enfant',6,true),
('hair','hommes','sous_categorie_produit','Forfaits',7,true),

('hair','hommes','nom_produit','Dégradé simple',1,true),
('hair','hommes','nom_produit','Dégradé américain',2,true),
('hair','hommes','nom_produit','Coupe à la tondeuse',3,true),
('hair','hommes','nom_produit','Coupe + Rasage',4,true),
('hair','hommes','nom_produit','Taille barbe',5,true),
('hair','hommes','nom_produit','Rasage complet',6,true),
('hair','hommes','nom_produit','Shampoing + Coupe',7,true),
('hair','hommes','nom_produit','Soin visage homme',8,true),
('hair','hommes','nom_produit','Coupe enfant',9,true),
('hair','hommes','nom_produit','Coupe afro',10,true),
('hair','hommes','nom_produit','Ligne de contour',11,true),
('hair','hommes','nom_produit','Dégradé + Barbe',12,true),
('hair','hommes','nom_produit','Coloration homme',13,true),

('hair','hommes','prix','500',1,true),
('hair','hommes','prix','1 000',2,true),
('hair','hommes','prix','1 500',3,true),
('hair','hommes','prix','2 000',4,true),
('hair','hommes','prix','2 500',5,true),
('hair','hommes','prix','3 000',6,true),
('hair','hommes','prix','3 500',7,true),
('hair','hommes','prix','5 000',8,true),

-- ── femmes (Coiffeur Femmes) ──────────────────────────────────
('hair','femmes','type_contenu','Tarif',1,true),
('hair','femmes','type_contenu','Catalogue de coiffures',2,true),
('hair','femmes','type_contenu','Carte des services',3,true),
('hair','femmes','type_contenu','Menu',4,true),
('hair','femmes','type_contenu','Liste des prestations',5,true),
('hair','femmes','type_contenu','Lookbook',6,true),

('hair','femmes','sous_categorie_produit','Tresses & Nattes',1,true),
('hair','femmes','sous_categorie_produit','Tissage & Extension',2,true),
('hair','femmes','sous_categorie_produit','Défrisage & Lissage',3,true),
('hair','femmes','sous_categorie_produit','Perruque & Wig',4,true),
('hair','femmes','sous_categorie_produit','Soins capillaires',5,true),
('hair','femmes','sous_categorie_produit','Coiffures naturelles',6,true),
('hair','femmes','sous_categorie_produit','Coiffures de mariage',7,true),
('hair','femmes','sous_categorie_produit','Coupe & Brushing',8,true),

('hair','femmes','nom_produit','Tresses collées',1,true),
('hair','femmes','nom_produit','Box braids',2,true),
('hair','femmes','nom_produit','Nattes simples',3,true),
('hair','femmes','nom_produit','Tissage brésilien',4,true),
('hair','femmes','nom_produit','Tissage naturel',5,true),
('hair','femmes','nom_produit','Défrisage',6,true),
('hair','femmes','nom_produit','Lissage kératine',7,true),
('hair','femmes','nom_produit','Pose de perruque (wig)',8,true),
('hair','femmes','nom_produit','Locks / Dreadlocks',9,true),
('hair','femmes','nom_produit','Twist',10,true),
('hair','femmes','nom_produit','Coiffure mariage',11,true),
('hair','femmes','nom_produit','Shampoing + Soin',12,true),
('hair','femmes','nom_produit','Coloration',13,true),
('hair','femmes','nom_produit','Coupe + Brushing',14,true),
('hair','femmes','nom_produit','Passion twists',15,true),

('hair','femmes','prix','2 000',1,true),
('hair','femmes','prix','3 000',2,true),
('hair','femmes','prix','5 000',3,true),
('hair','femmes','prix','7 500',4,true),
('hair','femmes','prix','10 000',5,true),
('hair','femmes','prix','15 000',6,true),
('hair','femmes','prix','20 000',7,true),
('hair','femmes','prix','25 000',8,true),
('hair','femmes','prix','35 000',9,true),
('hair','femmes','prix','50 000',10,true),

-- ── esthetique (Esthétique & Ongles) ─────────────────────────
('hair','esthetique','type_contenu','Tarif',1,true),
('hair','esthetique','type_contenu','Carte des soins',2,true),
('hair','esthetique','type_contenu','Menu beauté',3,true),
('hair','esthetique','type_contenu','Catalogue',4,true),
('hair','esthetique','type_contenu','Liste des prestations',5,true),
('hair','esthetique','type_contenu','Forfaits',6,true),

('hair','esthetique','sous_categorie_produit','Soins des ongles',1,true),
('hair','esthetique','sous_categorie_produit','Épilation',2,true),
('hair','esthetique','sous_categorie_produit','Soins du visage',3,true),
('hair','esthetique','sous_categorie_produit','Maquillage',4,true),
('hair','esthetique','sous_categorie_produit','Soins du corps',5,true),
('hair','esthetique','sous_categorie_produit','Sourcils & Cils',6,true),
('hair','esthetique','sous_categorie_produit','Forfaits beauté',7,true),
('hair','esthetique','sous_categorie_produit','Soins pieds',8,true),

('hair','esthetique','nom_produit','Pose gel ongles',1,true),
('hair','esthetique','nom_produit','Manucure simple',2,true),
('hair','esthetique','nom_produit','Pédicure',3,true),
('hair','esthetique','nom_produit','Pose capsules',4,true),
('hair','esthetique','nom_produit','Nail art',5,true),
('hair','esthetique','nom_produit','Épilation jambes',6,true),
('hair','esthetique','nom_produit','Épilation aisselles',7,true),
('hair','esthetique','nom_produit','Épilation visage',8,true),
('hair','esthetique','nom_produit','Soin visage hydratant',9,true),
('hair','esthetique','nom_produit','Maquillage journée',10,true),
('hair','esthetique','nom_produit','Maquillage mariée',11,true),
('hair','esthetique','nom_produit','Pose cils',12,true),
('hair','esthetique','nom_produit','Dessin sourcils',13,true),
('hair','esthetique','nom_produit','Gommage corps',14,true),
('hair','esthetique','nom_produit','Massage relaxant',15,true),

('hair','esthetique','prix','1 000',1,true),
('hair','esthetique','prix','2 000',2,true),
('hair','esthetique','prix','3 000',3,true),
('hair','esthetique','prix','5 000',4,true),
('hair','esthetique','prix','7 500',5,true),
('hair','esthetique','prix','10 000',6,true),
('hair','esthetique','prix','15 000',7,true),
('hair','esthetique','prix','20 000',8,true),
('hair','esthetique','prix','25 000',9,true),
('hair','esthetique','prix','35 000',10,true),

-- ══════════════════════════════════════════════════════════════
-- CATEGORY : sport
-- ══════════════════════════════════════════════════════════════

-- ── musculation (Musculation / Fitness) ───────────────────────
('sport','musculation','type_contenu','Tarif',1,true),
('sport','musculation','type_contenu','Carte des abonnements',2,true),
('sport','musculation','type_contenu','Catalogue de services',3,true),
('sport','musculation','type_contenu','Programme',4,true),
('sport','musculation','type_contenu','Liste des forfaits',5,true),

('sport','musculation','sous_categorie_produit','Abonnements',1,true),
('sport','musculation','sous_categorie_produit','Séances à l unité',2,true),
('sport','musculation','sous_categorie_produit','Coaching personnel',3,true),
('sport','musculation','sous_categorie_produit','Cours collectifs',4,true),
('sport','musculation','sous_categorie_produit','Suppléments & Nutrition',5,true),
('sport','musculation','sous_categorie_produit','Programmes spéciaux',6,true),

('sport','musculation','nom_produit','Abonnement mensuel',1,true),
('sport','musculation','nom_produit','Abonnement trimestriel',2,true),
('sport','musculation','nom_produit','Abonnement annuel',3,true),
('sport','musculation','nom_produit','Séance journalière',4,true),
('sport','musculation','nom_produit','Coaching personnel 1h',5,true),
('sport','musculation','nom_produit','Cours de zumba',6,true),
('sport','musculation','nom_produit','Cours de yoga',7,true),
('sport','musculation','nom_produit','Cours d aérobic',8,true),
('sport','musculation','nom_produit','Programme prise de masse',9,true),
('sport','musculation','nom_produit','Programme perte de poids',10,true),
('sport','musculation','nom_produit','Pack 10 séances',11,true),
('sport','musculation','nom_produit','Évaluation physique',12,true),
('sport','musculation','nom_produit','Cours de boxe',13,true),
('sport','musculation','nom_produit','Bilan nutritionnel',14,true),

('sport','musculation','prix','1 000',1,true),
('sport','musculation','prix','2 000',2,true),
('sport','musculation','prix','5 000',3,true),
('sport','musculation','prix','10 000',4,true),
('sport','musculation','prix','15 000',5,true),
('sport','musculation','prix','20 000',6,true),
('sport','musculation','prix','25 000',7,true),
('sport','musculation','prix','35 000',8,true),
('sport','musculation','prix','50 000',9,true),
('sport','musculation','prix','75 000',10,true),

-- ── reservation_terrain_foot ──────────────────────────────────
('sport','reservation_terrain_foot','type_contenu','Tarif horaire',1,true),
('sport','reservation_terrain_foot','type_contenu','Disponibilités',2,true),
('sport','reservation_terrain_foot','type_contenu','Grille tarifaire',3,true),
('sport','reservation_terrain_foot','type_contenu','Planning',4,true),
('sport','reservation_terrain_foot','type_contenu','Abonnements',5,true),

('sport','reservation_terrain_foot','sous_categorie_produit','Terrain 5 contre 5',1,true),
('sport','reservation_terrain_foot','sous_categorie_produit','Terrain 7 contre 7',2,true),
('sport','reservation_terrain_foot','sous_categorie_produit','Terrain 11 contre 11',3,true),
('sport','reservation_terrain_foot','sous_categorie_produit','Créneau avec éclairage',4,true),
('sport','reservation_terrain_foot','sous_categorie_produit','Vestiaires',5,true),
('sport','reservation_terrain_foot','sous_categorie_produit','Abonnements équipe',6,true),

('sport','reservation_terrain_foot','nom_produit','Location 1h terrain 5v5',1,true),
('sport','reservation_terrain_foot','nom_produit','Location 1h terrain 7v7',2,true),
('sport','reservation_terrain_foot','nom_produit','Location 1h terrain 11v11',3,true),
('sport','reservation_terrain_foot','nom_produit','Créneau matin (6h-12h)',4,true),
('sport','reservation_terrain_foot','nom_produit','Créneau soir (18h-22h)',5,true),
('sport','reservation_terrain_foot','nom_produit','Créneau nuit (22h-minuit)',6,true),
('sport','reservation_terrain_foot','nom_produit','Abonnement mensuel équipe',7,true),
('sport','reservation_terrain_foot','nom_produit','Tournoi week-end',8,true),
('sport','reservation_terrain_foot','nom_produit','Location demi-journée',9,true),
('sport','reservation_terrain_foot','nom_produit','Forfait groupe entreprise',10,true),

('sport','reservation_terrain_foot','prix','5 000',1,true),
('sport','reservation_terrain_foot','prix','8 000',2,true),
('sport','reservation_terrain_foot','prix','10 000',3,true),
('sport','reservation_terrain_foot','prix','12 000',4,true),
('sport','reservation_terrain_foot','prix','15 000',5,true),
('sport','reservation_terrain_foot','prix','20 000',6,true),
('sport','reservation_terrain_foot','prix','25 000',7,true),
('sport','reservation_terrain_foot','prix','50 000',8,true),

-- ── reservation_terrain_basket ────────────────────────────────
('sport','reservation_terrain_basket','type_contenu','Tarif horaire',1,true),
('sport','reservation_terrain_basket','type_contenu','Disponibilités',2,true),
('sport','reservation_terrain_basket','type_contenu','Planning',3,true),
('sport','reservation_terrain_basket','type_contenu','Abonnements',4,true),
('sport','reservation_terrain_basket','type_contenu','Grille tarifaire',5,true),

('sport','reservation_terrain_basket','sous_categorie_produit','Terrain couvert',1,true),
('sport','reservation_terrain_basket','sous_categorie_produit','Terrain extérieur',2,true),
('sport','reservation_terrain_basket','sous_categorie_produit','Demi-terrain',3,true),
('sport','reservation_terrain_basket','sous_categorie_produit','Créneau nocturne',4,true),
('sport','reservation_terrain_basket','sous_categorie_produit','Abonnements',5,true),

('sport','reservation_terrain_basket','nom_produit','Location 1h terrain complet',1,true),
('sport','reservation_terrain_basket','nom_produit','Location demi-terrain 1h',2,true),
('sport','reservation_terrain_basket','nom_produit','Créneau matin',3,true),
('sport','reservation_terrain_basket','nom_produit','Créneau après-midi',4,true),
('sport','reservation_terrain_basket','nom_produit','Créneau soirée',5,true),
('sport','reservation_terrain_basket','nom_produit','Abonnement hebdomadaire',6,true),
('sport','reservation_terrain_basket','nom_produit','Abonnement mensuel',7,true),
('sport','reservation_terrain_basket','nom_produit','Tournoi 3×3',8,true),
('sport','reservation_terrain_basket','nom_produit','Session libre',9,true),
('sport','reservation_terrain_basket','nom_produit','Forfait équipe',10,true),

('sport','reservation_terrain_basket','prix','3 000',1,true),
('sport','reservation_terrain_basket','prix','5 000',2,true),
('sport','reservation_terrain_basket','prix','7 500',3,true),
('sport','reservation_terrain_basket','prix','10 000',4,true),
('sport','reservation_terrain_basket','prix','12 000',5,true),
('sport','reservation_terrain_basket','prix','15 000',6,true),
('sport','reservation_terrain_basket','prix','20 000',7,true),
('sport','reservation_terrain_basket','prix','30 000',8,true),

-- ── arts_martiaux ─────────────────────────────────────────────
('sport','arts_martiaux','type_contenu','Tarif',1,true),
('sport','arts_martiaux','type_contenu','Planning cours',2,true),
('sport','arts_martiaux','type_contenu','Abonnements',3,true),
('sport','arts_martiaux','type_contenu','Programme entraînement',4,true),
('sport','arts_martiaux','type_contenu','Grille tarifaire',5,true),

('sport','arts_martiaux','sous_categorie_produit','Taekwondo',1,true),
('sport','arts_martiaux','sous_categorie_produit','Judo',2,true),
('sport','arts_martiaux','sous_categorie_produit','Karaté',3,true),
('sport','arts_martiaux','sous_categorie_produit','Lutte sénégalaise',4,true),
('sport','arts_martiaux','sous_categorie_produit','Boxe',5,true),
('sport','arts_martiaux','sous_categorie_produit','Cours collectifs',6,true),
('sport','arts_martiaux','sous_categorie_produit','Cours particuliers',7,true),

('sport','arts_martiaux','nom_produit','Cours taekwondo enfant',1,true),
('sport','arts_martiaux','nom_produit','Cours judo adulte',2,true),
('sport','arts_martiaux','nom_produit','Cours karaté débutant',3,true),
('sport','arts_martiaux','nom_produit','Entraînement lutte sénégalaise',4,true),
('sport','arts_martiaux','nom_produit','Session boxe 1h',5,true),
('sport','arts_martiaux','nom_produit','Abonnement mensuel club',6,true),
('sport','arts_martiaux','nom_produit','Cours particulier 1h',7,true),
('sport','arts_martiaux','nom_produit','Stage vacances',8,true),
('sport','arts_martiaux','nom_produit','Préparation compétition',9,true),
('sport','arts_martiaux','nom_produit','Cours self-défense',10,true),
('sport','arts_martiaux','nom_produit','Abonnement trimestriel',11,true),
('sport','arts_martiaux','nom_produit','Passage de grade',12,true),

('sport','arts_martiaux','prix','2 000',1,true),
('sport','arts_martiaux','prix','3 000',2,true),
('sport','arts_martiaux','prix','5 000',3,true),
('sport','arts_martiaux','prix','7 500',4,true),
('sport','arts_martiaux','prix','10 000',5,true),
('sport','arts_martiaux','prix','15 000',6,true),
('sport','arts_martiaux','prix','25 000',7,true),
('sport','arts_martiaux','prix','35 000',8,true);
